### PR TITLE
Create It's my fault I hurt her.md

### PR DESCRIPTION
**Pull request by Xmy954272**

### CODE REVIEW

**Comment by Owencjs** [comment]
xmy你怎么能这样！doge

**Review by WillHouMoe — COMMENTED** [review]
what the shit are you saying

**Comment by Xmy954272** [comment]
992619

**Comment by Owencjs** [comment]
> 992619

?

**Comment by Arthurjiang2009** [comment]
> 992619

wtf is this

**Comment by Owencjs** [comment]
> > 992619
> 
> wtf is this

you are here!!!

**Comment by WillHouMoe** [comment]
> > 992619
> 
> wtf is this

no idea

**Comment by Xmy954272** [comment]
9+92+6+19

**Comment by Xmy954272** [comment]
atomic number

**Comment by Arthurjiang2009** [comment]
> > > 992619
> > 
> > 
> > wtf is this
> 
> you are here!!!

man im back

**Pull request closed without merging**
