### PR TITLE
pls mmmmmeeeeerrrrrgggggeeeee

### PR DESCRIPTION
**Pull request by Arthurjiang2009**

### CODE REVIEW

**Comment by WillHouMoe** [comment]
Thanks&good writing!
I will merge it as soon as i get home

**Review by WillHouMoe — APPROVED** [review]
Approve

**Comment by Owencjs** [comment]
新一代劳模诞生了doge

**Comment by Arthurjiang2009** [comment]
> 新一代劳模诞生了doge

6

**Pull request merged**
